package com.project.moviebooking.rest.helper;

import java.util.List;

/**
 *
 * @author Rohit
 * @param <E>
 * @param <REQ>
 * @param <LRESPONSE>
 * @param <ADRESPONSE>
 * @param <DRESPONSE>
 */
public abstract class AbstractHelper<E, REQ, LRESPONSE, DRESPONSE, ADRESPONSE> {

	public abstract E getEntity(REQ request) throws Exception;

	public abstract List<LRESPONSE> getListItemTypeResponse(List<E> entityList);

	public abstract DRESPONSE getDetailResponse(E entity);

	public abstract ADRESPONSE getDetailForAdminResponse(E entity);

//	public Boolean uploadImage(Object entity, REQ request) {
//		boolean flag = false;
//		int coverImageIndex = 0;
//		if (request instanceof CoverImageRequest && entity instanceof CoverImage) {
//			String coverImage = ((CoverImageRequest) request).getCoverImage();
//			if (StringUtils.isNotEmpty(coverImage)) {
//				try {
//					coverImageIndex = Integer.parseInt(coverImage);
//					if (coverImageIndex <= 0) {
//						coverImageIndex = 0;
//					}
//				} catch (NumberFormatException ne) {
//					try {
//						Media image = new Media();
//						image.setPath(fileUpload.uploadBase64StringFileToPublicBucket(
//								entity.getClass().getSimpleName() + "/" + ((AutoGeneratedId) entity).getId(),
//								RandomStringUtils.randomAlphanumeric(6),
//								((CoverImageRequest) request).getCoverImage()));
//						image = (Media) imageService.save(image);
//						((CoverImage) entity).setCoverImageId(image);
//					} catch (RuntimeException ex) {
//						java.util.logging.Logger.getLogger(AbstractHelper.class.getName()).log(Level.SEVERE, null, ex);
//					} catch (IOException ex) {
//						java.util.logging.Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
//					}
//					flag = true;
//				}
//			}
//		}
//		
//		if (request instanceof WebCoverImageRequest && entity instanceof WebCoverImage) {
//			String webCoverImage = ((WebCoverImageRequest) request).getWebCoverImage();
//			if (StringUtils.isNotEmpty(webCoverImage)) {
//				try {
//					coverImageIndex = Integer.parseInt(webCoverImage);
//					if (coverImageIndex <= 0) {
//						coverImageIndex = 0;
//					}
//				} catch (NumberFormatException ne) {
//					try {
//						Media image = new Media();
//						image.setPath(fileUpload.uploadBase64StringFileToPublicBucket(
//								entity.getClass().getSimpleName() + "/" + ((AutoGeneratedId) entity).getId(),
//								RandomStringUtils.randomAlphanumeric(6),
//								((WebCoverImageRequest) request).getWebCoverImage()));
//						image = (Media) imageService.save(image);
//						((WebCoverImage) entity).setWebCoverImageId(image);
//					} catch (RuntimeException ex) {
//						java.util.logging.Logger.getLogger(AbstractHelper.class.getName()).log(Level.SEVERE, null, ex);
//					} catch (IOException ex) {
//						java.util.logging.Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
//					}
//					flag = true;
//				}
//			}
//		}
//		
//		if (entity instanceof ImageList && request instanceof ImageListRequest) {
//
//			if (((ImageListRequest) request).getBase64ImageStrings() != null
//					&& !((ImageListRequest) request).getBase64ImageStrings().isEmpty()) {
//				if (((ImageList) entity).getImages() == null) {
//					((ImageList) entity).setImages(new ArrayList());
//				}
//				((ImageListRequest) request).getBase64ImageStrings().forEach((base64ImageString) -> {
//					if (base64ImageString != null && !base64ImageString.isEmpty()) {
//						try {
//							Media image = new Media();
//							image.setPath(fileUpload.uploadBase64StringFileToPublicBucket(
//									entity.getClass().getSimpleName() + "/" + ((AutoGeneratedId) entity).getId(),
//									RandomStringUtils.randomAlphanumeric(6), base64ImageString));
//							imageService.save(image);
//							((ImageList) entity).getImages().add(image);
//						} catch (RuntimeException ex) {
//							java.util.logging.Logger.getLogger(AbstractHelper.class.getName()).log(Level.SEVERE, null, ex);
//						} catch (IOException ex) {
//							java.util.logging.Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
//						}
//					}
//				});
//				flag = true;
//			}
//		}
//		if (request instanceof CoverImageRequest && entity instanceof CoverImage && entity instanceof ImageList
//				&& request instanceof ImageListRequest) {
//			if (!ObjectUtils.isEmpty(((ImageList) entity).getImages())) {
//				((CoverImage) entity).setCoverImageId(((ImageList) entity).getImages().get(coverImageIndex));
//			} else {
//				((CoverImage) entity).setCoverImageId(null);
//			}
//		}
//		try {
//			if (request instanceof ImageListRequest) {
//				List<String> deletedImages = ((ImageListRequest) request).getDeletedImages();
//				if (!ObjectUtils.isEmpty(deletedImages)) {
//					for (String deletedImage : deletedImages) {
//						imageService.deleteMedia(deletedImage);
//						fileUpload.deleteFileByS3(deletedImage);
//					}
//				}
//			}
//		} catch (RuntimeException | IOException ex) {
//			Logger.getLogger(AbstractHelper.class.getName()).log(Level.SEVERE, null, ex);
//		}
//		return flag;
//	}
}
